[headers]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://public.tableau.com; connect-src 'self' https://public.tableau.com; frame-ancestors 'self' https://public.tableau.com; frame-src 'self' https://public.tableau.com; script-src 'self' 'unsafe-inline' https://public.tableau.com; style-src 'self' 'unsafe-inline' https://public.tableau.com"